export type Country = { id: string; cc: string; n: string };
// Worldwide dial codes. The first group is shown at the top of the list.
export const COUNTRIES: Country[] = [
  { id: "BD", cc: "880", n: "Bangladesh" },
  { id: "SA", cc: "966", n: "Saudi Arabia" },
  { id: "OM", cc: "968", n: "Oman" },
  { id: "AE", cc: "971", n: "United Arab Emirates" },
  { id: "KW", cc: "965", n: "Kuwait" },
  { id: "QA", cc: "974", n: "Qatar" },
  { id: "BH", cc: "973", n: "Bahrain" },
  { id: "MY", cc: "60", n: "Malaysia" },
  { id: "SG", cc: "65", n: "Singapore" },
  { id: "IN", cc: "91", n: "India" },
  { id: "PK", cc: "92", n: "Pakistan" },
  { id: "GB", cc: "44", n: "United Kingdom" },
  { id: "US", cc: "1", n: "United States" },
  { id: "IT", cc: "39", n: "Italy" },
  { id: "AC", cc: "247", n: "AC" },
  { id: "AF", cc: "93", n: "Afghanistan" },
  { id: "AX", cc: "358", n: "Aland Islands" },
  { id: "AL", cc: "355", n: "Albania" },
  { id: "DZ", cc: "213", n: "Algeria" },
  { id: "AS", cc: "1", n: "American Samoa" },
  { id: "AD", cc: "376", n: "Andorra" },
  { id: "AO", cc: "244", n: "Angola" },
  { id: "AI", cc: "1", n: "Anguilla" },
  { id: "AG", cc: "1", n: "Antigua and Barbuda" },
  { id: "AR", cc: "54", n: "Argentina" },
  { id: "AM", cc: "374", n: "Armenia" },
  { id: "AW", cc: "297", n: "Aruba" },
  { id: "AU", cc: "61", n: "Australia" },
  { id: "AT", cc: "43", n: "Austria" },
  { id: "AZ", cc: "994", n: "Azerbaijan" },
  { id: "BS", cc: "1", n: "Bahamas" },
  { id: "BB", cc: "1", n: "Barbados" },
  { id: "BY", cc: "375", n: "Belarus" },
  { id: "BE", cc: "32", n: "Belgium" },
  { id: "BZ", cc: "501", n: "Belize" },
  { id: "BJ", cc: "229", n: "Benin" },
  { id: "BM", cc: "1", n: "Bermuda" },
  { id: "BT", cc: "975", n: "Bhutan" },
  { id: "BO", cc: "591", n: "Bolivia" },
  { id: "BQ", cc: "599", n: "Bonaire, Sint Eustatius and Saba" },
  { id: "BA", cc: "387", n: "Bosnia and Herzegovina" },
  { id: "BW", cc: "267", n: "Botswana" },
  { id: "BR", cc: "55", n: "Brazil" },
  { id: "IO", cc: "246", n: "British Indian Ocean Territory" },
  { id: "BN", cc: "673", n: "Brunei" },
  { id: "BG", cc: "359", n: "Bulgaria" },
  { id: "BF", cc: "226", n: "Burkina Faso" },
  { id: "BI", cc: "257", n: "Burundi" },
  { id: "CV", cc: "238", n: "Cabo Verde" },
  { id: "KH", cc: "855", n: "Cambodia" },
  { id: "CM", cc: "237", n: "Cameroon" },
  { id: "CA", cc: "1", n: "Canada" },
  { id: "KY", cc: "1", n: "Cayman Islands" },
  { id: "CF", cc: "236", n: "Central African Republic" },
  { id: "TD", cc: "235", n: "Chad" },
  { id: "CL", cc: "56", n: "Chile" },
  { id: "CN", cc: "86", n: "China" },
  { id: "CX", cc: "61", n: "Christmas Island" },
  { id: "CC", cc: "61", n: "Cocos (Keeling) Islands" },
  { id: "CO", cc: "57", n: "Colombia" },
  { id: "KM", cc: "269", n: "Comoros" },
  { id: "CG", cc: "242", n: "Congo" },
  { id: "CK", cc: "682", n: "Cook Islands" },
  { id: "CR", cc: "506", n: "Costa Rica" },
  { id: "CI", cc: "225", n: "Cote d'Ivoire" },
  { id: "HR", cc: "385", n: "Croatia" },
  { id: "CU", cc: "53", n: "Cuba" },
  { id: "CW", cc: "599", n: "Curacao" },
  { id: "CY", cc: "357", n: "Cyprus" },
  { id: "CZ", cc: "420", n: "Czechia" },
  { id: "CD", cc: "243", n: "DR Congo" },
  { id: "DK", cc: "45", n: "Denmark" },
  { id: "DJ", cc: "253", n: "Djibouti" },
  { id: "DM", cc: "1", n: "Dominica" },
  { id: "DO", cc: "1", n: "Dominican Republic" },
  { id: "EC", cc: "593", n: "Ecuador" },
  { id: "EG", cc: "20", n: "Egypt" },
  { id: "SV", cc: "503", n: "El Salvador" },
  { id: "GQ", cc: "240", n: "Equatorial Guinea" },
  { id: "ER", cc: "291", n: "Eritrea" },
  { id: "EE", cc: "372", n: "Estonia" },
  { id: "SZ", cc: "268", n: "Eswatini" },
  { id: "ET", cc: "251", n: "Ethiopia" },
  { id: "FK", cc: "500", n: "Falkland Islands (Malvinas)" },
  { id: "FO", cc: "298", n: "Faroe Islands" },
  { id: "FJ", cc: "679", n: "Fiji" },
  { id: "FI", cc: "358", n: "Finland" },
  { id: "FR", cc: "33", n: "France" },
  { id: "GF", cc: "594", n: "French Guiana" },
  { id: "PF", cc: "689", n: "French Polynesia" },
  { id: "GA", cc: "241", n: "Gabon" },
  { id: "GM", cc: "220", n: "Gambia" },
  { id: "GE", cc: "995", n: "Georgia" },
  { id: "DE", cc: "49", n: "Germany" },
  { id: "GH", cc: "233", n: "Ghana" },
  { id: "GI", cc: "350", n: "Gibraltar" },
  { id: "GR", cc: "30", n: "Greece" },
  { id: "GL", cc: "299", n: "Greenland" },
  { id: "GD", cc: "1", n: "Grenada" },
  { id: "GP", cc: "590", n: "Guadeloupe" },
  { id: "GU", cc: "1", n: "Guam" },
  { id: "GT", cc: "502", n: "Guatemala" },
  { id: "GG", cc: "44", n: "Guernsey" },
  { id: "GN", cc: "224", n: "Guinea" },
  { id: "GW", cc: "245", n: "Guinea-Bissau" },
  { id: "GY", cc: "592", n: "Guyana" },
  { id: "HT", cc: "509", n: "Haiti" },
  { id: "HN", cc: "504", n: "Honduras" },
  { id: "HK", cc: "852", n: "Hong Kong" },
  { id: "HU", cc: "36", n: "Hungary" },
  { id: "IS", cc: "354", n: "Iceland" },
  { id: "ID", cc: "62", n: "Indonesia" },
  { id: "IR", cc: "98", n: "Iran" },
  { id: "IQ", cc: "964", n: "Iraq" },
  { id: "IE", cc: "353", n: "Ireland" },
  { id: "IM", cc: "44", n: "Isle of Man" },
  { id: "IL", cc: "972", n: "Israel" },
  { id: "JM", cc: "1", n: "Jamaica" },
  { id: "JP", cc: "81", n: "Japan" },
  { id: "JE", cc: "44", n: "Jersey" },
  { id: "JO", cc: "962", n: "Jordan" },
  { id: "KZ", cc: "7", n: "Kazakhstan" },
  { id: "KE", cc: "254", n: "Kenya" },
  { id: "KI", cc: "686", n: "Kiribati" },
  { id: "XK", cc: "383", n: "Kosovo" },
  { id: "KG", cc: "996", n: "Kyrgyzstan" },
  { id: "LA", cc: "856", n: "Laos" },
  { id: "LV", cc: "371", n: "Latvia" },
  { id: "LB", cc: "961", n: "Lebanon" },
  { id: "LS", cc: "266", n: "Lesotho" },
  { id: "LR", cc: "231", n: "Liberia" },
  { id: "LY", cc: "218", n: "Libya" },
  { id: "LI", cc: "423", n: "Liechtenstein" },
  { id: "LT", cc: "370", n: "Lithuania" },
  { id: "LU", cc: "352", n: "Luxembourg" },
  { id: "MO", cc: "853", n: "Macau" },
  { id: "MG", cc: "261", n: "Madagascar" },
  { id: "MW", cc: "265", n: "Malawi" },
  { id: "MV", cc: "960", n: "Maldives" },
  { id: "ML", cc: "223", n: "Mali" },
  { id: "MT", cc: "356", n: "Malta" },
  { id: "MH", cc: "692", n: "Marshall Islands" },
  { id: "MQ", cc: "596", n: "Martinique" },
  { id: "MR", cc: "222", n: "Mauritania" },
  { id: "MU", cc: "230", n: "Mauritius" },
  { id: "YT", cc: "262", n: "Mayotte" },
  { id: "MX", cc: "52", n: "Mexico" },
  { id: "FM", cc: "691", n: "Micronesia" },
  { id: "MD", cc: "373", n: "Moldova" },
  { id: "MC", cc: "377", n: "Monaco" },
  { id: "MN", cc: "976", n: "Mongolia" },
  { id: "ME", cc: "382", n: "Montenegro" },
  { id: "MS", cc: "1", n: "Montserrat" },
  { id: "MA", cc: "212", n: "Morocco" },
  { id: "MZ", cc: "258", n: "Mozambique" },
  { id: "MM", cc: "95", n: "Myanmar" },
  { id: "NA", cc: "264", n: "Namibia" },
  { id: "NR", cc: "674", n: "Nauru" },
  { id: "NP", cc: "977", n: "Nepal" },
  { id: "NL", cc: "31", n: "Netherlands" },
  { id: "NC", cc: "687", n: "New Caledonia" },
  { id: "NZ", cc: "64", n: "New Zealand" },
  { id: "NI", cc: "505", n: "Nicaragua" },
  { id: "NE", cc: "227", n: "Niger" },
  { id: "NG", cc: "234", n: "Nigeria" },
  { id: "NU", cc: "683", n: "Niue" },
  { id: "NF", cc: "672", n: "Norfolk Island" },
  { id: "KP", cc: "850", n: "North Korea" },
  { id: "MK", cc: "389", n: "North Macedonia" },
  { id: "MP", cc: "1", n: "Northern Mariana Islands" },
  { id: "NO", cc: "47", n: "Norway" },
  { id: "PW", cc: "680", n: "Palau" },
  { id: "PS", cc: "970", n: "Palestine" },
  { id: "PA", cc: "507", n: "Panama" },
  { id: "PG", cc: "675", n: "Papua New Guinea" },
  { id: "PY", cc: "595", n: "Paraguay" },
  { id: "PE", cc: "51", n: "Peru" },
  { id: "PH", cc: "63", n: "Philippines" },
  { id: "PL", cc: "48", n: "Poland" },
  { id: "PT", cc: "351", n: "Portugal" },
  { id: "PR", cc: "1", n: "Puerto Rico" },
  { id: "RE", cc: "262", n: "Reunion" },
  { id: "RO", cc: "40", n: "Romania" },
  { id: "RU", cc: "7", n: "Russia" },
  { id: "RW", cc: "250", n: "Rwanda" },
  { id: "BL", cc: "590", n: "Saint Barthelemy" },
  { id: "SH", cc: "290", n: "Saint Helena, Ascension and Tristan da Cunha" },
  { id: "KN", cc: "1", n: "Saint Kitts and Nevis" },
  { id: "LC", cc: "1", n: "Saint Lucia" },
  { id: "MF", cc: "590", n: "Saint Martin (French part)" },
  { id: "PM", cc: "508", n: "Saint Pierre and Miquelon" },
  { id: "VC", cc: "1", n: "Saint Vincent and the Grenadines" },
  { id: "WS", cc: "685", n: "Samoa" },
  { id: "SM", cc: "378", n: "San Marino" },
  { id: "ST", cc: "239", n: "Sao Tome and Principe" },
  { id: "SN", cc: "221", n: "Senegal" },
  { id: "RS", cc: "381", n: "Serbia" },
  { id: "SC", cc: "248", n: "Seychelles" },
  { id: "SL", cc: "232", n: "Sierra Leone" },
  { id: "SX", cc: "1", n: "Sint Maarten (Dutch part)" },
  { id: "SK", cc: "421", n: "Slovakia" },
  { id: "SI", cc: "386", n: "Slovenia" },
  { id: "SB", cc: "677", n: "Solomon Islands" },
  { id: "SO", cc: "252", n: "Somalia" },
  { id: "ZA", cc: "27", n: "South Africa" },
  { id: "KR", cc: "82", n: "South Korea" },
  { id: "SS", cc: "211", n: "South Sudan" },
  { id: "ES", cc: "34", n: "Spain" },
  { id: "LK", cc: "94", n: "Sri Lanka" },
  { id: "SD", cc: "249", n: "Sudan" },
  { id: "SR", cc: "597", n: "Suriname" },
  { id: "SJ", cc: "47", n: "Svalbard and Jan Mayen" },
  { id: "SE", cc: "46", n: "Sweden" },
  { id: "CH", cc: "41", n: "Switzerland" },
  { id: "SY", cc: "963", n: "Syria" },
  { id: "TA", cc: "290", n: "TA" },
  { id: "TW", cc: "886", n: "Taiwan" },
  { id: "TJ", cc: "992", n: "Tajikistan" },
  { id: "TZ", cc: "255", n: "Tanzania" },
  { id: "TH", cc: "66", n: "Thailand" },
  { id: "TL", cc: "670", n: "Timor-Leste" },
  { id: "TG", cc: "228", n: "Togo" },
  { id: "TK", cc: "690", n: "Tokelau" },
  { id: "TO", cc: "676", n: "Tonga" },
  { id: "TT", cc: "1", n: "Trinidad and Tobago" },
  { id: "TN", cc: "216", n: "Tunisia" },
  { id: "TR", cc: "90", n: "Turkey" },
  { id: "TM", cc: "993", n: "Turkmenistan" },
  { id: "TC", cc: "1", n: "Turks and Caicos Islands" },
  { id: "TV", cc: "688", n: "Tuvalu" },
  { id: "UG", cc: "256", n: "Uganda" },
  { id: "UA", cc: "380", n: "Ukraine" },
  { id: "UY", cc: "598", n: "Uruguay" },
  { id: "UZ", cc: "998", n: "Uzbekistan" },
  { id: "VU", cc: "678", n: "Vanuatu" },
  { id: "VA", cc: "39", n: "Vatican City" },
  { id: "VE", cc: "58", n: "Venezuela" },
  { id: "VN", cc: "84", n: "Vietnam" },
  { id: "VG", cc: "1", n: "Virgin Islands, British" },
  { id: "VI", cc: "1", n: "Virgin Islands, U.S." },
  { id: "WF", cc: "681", n: "Wallis and Futuna" },
  { id: "EH", cc: "212", n: "Western Sahara" },
  { id: "YE", cc: "967", n: "Yemen" },
  { id: "ZM", cc: "260", n: "Zambia" },
  { id: "ZW", cc: "263", n: "Zimbabwe" },
];
